# Generated by Django 3.2.20 on 2024-09-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolmanagements',
            name='Heroku_External_ID',
            field=models.IntegerField(default=1),
        ),
    ]
